config:
  instance:
    root: ${BANALYTICS_HOME}
    software-update:
      on-first-run-enable: true

spring:
  application:
    name: Behaviour Analysitcs
  messages:
    encoding: UTF-8
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  datasource:
    url: jdbc:derby:directory:${config.instance.root}/derby/banalytics;create=true
    driver-class-name: org.apache.derby.iapi.jdbc.AutoloadedDriver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: com.banalytics.box.jpa.CustomDialect
        jdbc.lob.non_contextual_creation: true
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        show_sql: false
        jdbc:
          time_zone: UTC

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    remoteip:
      remote-ip-header: "x-forwarded-for"
      protocol-header: "x-forwarded-proto"
  servlet.encoding.charset: UTF-8

  compression:
    enabled: off
    mime-types: text/html, text/css, application/javascript, application/json
    min-response-size: 2KB
  servlet:
    session:
      timeout: 1h
  ssl:
    enabled: false
#    key-store-type: PKCS12
#    key-store: classpath:ssl/banalytics.p12
#    key-store-password: 'keystorepassword'
#    key-alias: banalytics

logging:
  level:
    org.springframework: WARN
    com.banalytics.box: INFO